require: rubocop-performance

AllCops:
  Exclude:
    - "vendor/**/*"
    - "spec/spec_helper.rb"
    - "lib/mongo_clarify/investigate_ruby2_7.rb"

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Style/LambdaCall:
  Exclude:
    - "lib/mongo_clarify/investigate.rb"
