#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'JSON'
require 'mongo-clarify'

file = File.read("./#{ARGV[0]}")
explain = JSON.parse(file, symbolize_names: true)

MongoClarify.run(explain)
